## Classification Model Evaluation

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix

1) Given the following confusion matrix, evaluate (by hand) the model's performance.


|               | pred dog   | pred cat   |
|:------------  |-----------:|-----------:|
| actual dog    |         46 |         7  |
| actual cat    |         13 |         34 |

In the context of this problem, what is a false positive?

- **Choosing Dog prediction as the positive case. A false positive would be when we predict a dog but then it turns out to be a cat.**

In the context of this problem, what is a false negative?

- **Choosing Dog prediction as the positive case. A false negative in this case would be when we predict a cat but then it turns out to be a dog.**

How would you describe this model?

In [ ]:
- Dog Positive case
- Cat Negative case

tp = 46
tn = 34
fp = 7
fn = 13

accuracy = (tp + tn) / (tp + tn + fp + fn)
recall = tp / (tp + fn)
precision = tp / (tp + fp)



2) You are working as a data scientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here.

Use the predictions dataset and pandas to help answer the following questions:

An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?


In [ ]:
c3 = pd.read_csv('c3.csv')
c3.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

In [7]:
pd.crosstab(c3.actual, c3.model1)

model1     Defect  No Defect
actual                      
Defect          8          8
No Defect       2        182

In [8]:
pd.crosstab(c3.actual, c3.model2)

model2     Defect  No Defect
actual                      
Defect          9          7
No Defect      81        103

In [9]:
pd.crosstab(c3.actual, c3.model3)

model3     Defect  No Defect
actual                      
Defect         13          3
No Defect      86         98

In [10]:
confusion_matrix(c3.actual, c3.model1, labels = ('No Defect','Defect'))

array([[182,   2],
       [  8,   8]])

In [11]:
confusion_matrix(c3.actual, c3.model2, labels = ('No Defect','Defect'))

array([[103,  81],
       [  7,   9]])

In [12]:
confusion_matrix(c3.actual, c3.model3, labels = ('No Defect','Defect'))

array([[98, 86],
       [ 3, 13]])

In [14]:
c3['baseline_prediction'] = 'Defect'
c3.head()

actual     model1  model2     model3 baseline_prediction
0  No Defect  No Defect  Defect  No Defect              Defect
1  No Defect  No Defect  Defect     Defect              Defect
2  No Defect  No Defect  Defect  No Defect              Defect
3  No Defect     Defect  Defect     Defect              Defect
4  No Defect  No Defect  Defect  No Defect              Defect

In [18]:
model1_accuracy = (c3.model1 == c3.actual).mean()
model2_accuracy = (c3.model2 == c3.actual).mean()
model3_accuracy = (c3.model3 == c3.actual).mean()
baseline_accuracy = (c3.baseline_prediction == c3.actual).mean()

print(f'    model 1 accuracy: {model1_accuracy:.2%}')
print(f'    model 2 accuracy: {model2_accuracy:.2%}')
print(f'    model 3 accuracy: {model3_accuracy:.2%}')
print(f'   baseline accuracy: {baseline_accuracy:.2%}')

    model 1 accuracy: 95.00%
    model 2 accuracy: 56.00%
    model 3 accuracy: 55.50%
   baseline accuracy: 8.00%


In [19]:
subset = c3[c3.actual == 'Defect']

model1_recall = (subset.model1 == subset.actual).mean()
model2_recall = (subset.model2 == subset.actual).mean()
model3_recall = (subset.model3 == subset.actual).mean()
baseline_recall = (subset.baseline_prediction == subset.actual).mean()

print(f'   model 1 recall: {model1_recall:.2%}')
print(f'   model 2 recall: {model2_recall:.2%}')
print(f'   model 3 recall: {model3_recall:.2%}')
print(f'  baseline recall: {baseline_recall:.2%}')

   model 1 recall: 50.00%
   model 2 recall: 56.25%
   model 3 recall: 81.25%
  baseline recall: 100.00%


In [21]:
subset = c3[c3.model1 == 'Defect']
model1_precision = (subset.model1 == subset.actual).mean()

subset = c3[c3.model2 == 'Defect']
model2_precision = (subset.model2 == subset.actual).mean()

subset = c3[c3.model3 == 'Defect']
model3_precision = (subset.model3 == subset.actual).mean()

subset = c3[c3.baseline_prediction == 'Defect']
baseline_precision = (subset.baseline_prediction == subset.actual).mean()

print(f'  model 1 precision: {model1_precision:.2%}')
print(f'  model 2 precision: {model2_precision:.2%}')
print(f'  model 3 precision: {model3_precision:.2%}')
print(f'baseline precision: {baseline_precision:.2%}')

  model 1 precision: 80.00%
  model 2 precision: 10.00%
  model 3 precision: 13.13%
baseline precision: 8.00%


- **Recall would seem to be an appropriate evaluation metric. We want to see how accurate our model is at predicting Defects so we want to know when we are both right and wrong about the actual positive cases of defects. Using this metric model 3 would seem to be the best case.**

Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

- **We want to be sure that our positive predictions are correct so we would want to use precision. In this case model 1 would be the best fit.**

3) You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).

At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).

Several models have already been developed with the data, and you can find their results here.

Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:

In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?


Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? For Phase II?

Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? For Phase II?

4) Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.

sklearn.metrics.accuracy_score

sklearn.metrics.precision_score

sklearn.metrics.recall_score

sklearn.metrics.classification_report